package:
  dir: F:\upload
#server:
#  port: 5432
mybatis:
  mapper-locations: classpath*:mapper/Mapper.xml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudladder
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_cloudladderserver
    baseline-on-migrate: true
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
